### ISSUE TITLE
Getting cert error when pod starting

### ISSUE THREAD

**Issue by macon** [wongnai/kube-slack#43]
Get the following pod logs:
```
{"name":"kube-slack","hostname":"kube-slack-56d459fc44-fxq6g","pid":1,"level":30,"msg":"KUBE_NAMESPACE_ONLY not set. Watching pods in ALL namespaces.","time":"2018-10-17T09:21:20.864Z","v":0}
{"name":"kube-slack","hostname":"kube-slack-56d459fc44-fxq6g","pid":1,"level":30,"msg":"Kubernetes monitors started","time":"2018-10-17T09:21:20.890Z","v":0}
(node:1) UnhandledPromiseRejectionWarning: Error: unable to get issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1047:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:629:8)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by whs** [comment]
Are you using kubeconfig option? Try testing that kubectl works with your configuration. If it work but ours doesn't then as a last resort, set `insecure-skip-tls-verify: true` in cluster section.

**Comment by macon** [comment]
This was due to the service account certificate not containing the full certificate chain. We're using a custom kubeconfig to work around.
